compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU  # DEEPSPEED -> MULTI_GPU로 변경
downcast_bf16: 'no'
gpu_ids: 0,1                 # 모든 GPU 사용
machine_rank: 0
main_training_function: main
mixed_precision: bf16        # bfloat16 유지
num_machines: 1
num_processes: 2             # [주의] 실제 사용 가능한 GPU 개수로 설정하세요 (예: 1, 2, 4, 8)
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false